// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
)

const (
	DeveloperTokenScopes = "DeveloperToken.Scopes"
)

// BuildPushOptions defines model for BuildPushOptions.
type BuildPushOptions struct {
	Password string `json:"password"`
	Repo     string `json:"repo"`
	Tag      string `json:"tag"`
	Username string `json:"username"`
}

// ModuleRequirements defines model for ModuleRequirements.
type ModuleRequirements struct {
	Rbac *RBACRequirements `json:"rbac,omitempty"`
}

// PublishComponent defines model for PublishComponent.
type PublishComponent struct {
	Description string                  `json:"description"`
	Info        *string                 `json:"info,omitempty"`
	Name        string                  `json:"name"`
	Ports       *[]PublishComponentPort `json:"ports,omitempty"`
	Tags        *[]string               `json:"tags,omitempty"`
}

// PublishComponentPort defines model for PublishComponentPort.
type PublishComponentPort struct {
	DefaultData *map[string]interface{} `json:"default_data,omitempty"`
	Label       *string                 `json:"label,omitempty"`
	Name        string                  `json:"name"`
	Position    *int                    `json:"position,omitempty"`
	Schema      *map[string]interface{} `json:"schema,omitempty"`
	Source      bool                    `json:"source"`
}

// PublishModuleRequest defines model for PublishModuleRequest.
type PublishModuleRequest struct {
	Components   []PublishComponent  `json:"components"`
	Description  *string             `json:"description,omitempty"`
	Info         *string             `json:"info,omitempty"`
	Name         string              `json:"name"`
	Requirements *ModuleRequirements `json:"requirements,omitempty"`

	// SdkVersion SDK version used to build this module
	SdkVersion *string `json:"sdk_version,omitempty"`
	Version    string  `json:"version"`
}

// PublishModuleResult defines model for PublishModuleResult.
type PublishModuleResult struct {
	Module  *PublishModuleVersion `json:"module,omitempty"`
	Options *BuildPushOptions     `json:"options,omitempty"`
}

// PublishModuleVersion defines model for PublishModuleVersion.
type PublishModuleVersion struct {
	Id      string `json:"id"`
	Name    string `json:"name"`
	Version string `json:"version"`
}

// RBACRequirements defines model for RBACRequirements.
type RBACRequirements struct {
	// EnableKubernetesResourceAccess Enable access to pods, services, deployments, ingresses
	EnableKubernetesResourceAccess *bool       `json:"enableKubernetesResourceAccess,omitempty"`
	ExtraRules                     *[]RBACRule `json:"extraRules,omitempty"`
}

// RBACRule defines model for RBACRule.
type RBACRule struct {
	ApiGroups *[]string `json:"apiGroups,omitempty"`
	Resources *[]string `json:"resources,omitempty"`
	Verbs     *[]string `json:"verbs,omitempty"`
}

// SolutionDetails Full solution structure returned by `/v1/solutions/{uuid}`.
// Contains every flow with its nodes, edges, and configurations,
// plus any solution-level variables.
type SolutionDetails struct {
	Description string                    `json:"description"`
	Flows       []SolutionFlow            `json:"flows"`
	Tags        *[]string                 `json:"tags,omitempty"`
	Title       string                    `json:"title"`
	Uuid        string                    `json:"uuid"`
	Variables   *[]map[string]interface{} `json:"variables,omitempty"`
}

// SolutionEdge defines model for SolutionEdge.
type SolutionEdge struct {
	Configuration *map[string]interface{} `json:"configuration,omitempty"`
	Source        string                  `json:"source"`
	SourceHandle  string                  `json:"source_handle"`
	Target        string                  `json:"target"`
	TargetHandle  string                  `json:"target_handle"`
}

// SolutionFlow defines model for SolutionFlow.
type SolutionFlow struct {
	Edges []SolutionEdge `json:"edges"`
	Nodes []SolutionNode `json:"nodes"`
	Title string         `json:"title"`
}

// SolutionNode defines model for SolutionNode.
type SolutionNode struct {
	Component string                  `json:"component"`
	Id        string                  `json:"id"`
	Module    string                  `json:"module"`
	Position  *map[string]interface{} `json:"position,omitempty"`
	Settings  *map[string]interface{} `json:"settings,omitempty"`
}

// SolutionSearchResponse defines model for SolutionSearchResponse.
type SolutionSearchResponse struct {
	Results []SolutionSummary `json:"results"`
}

// SolutionSummary Brief overview of a solution returned by `/v1/solutions/search`.
// Carries enough for the caller to render a result row and decide
// whether to fetch the full details.
type SolutionSummary struct {
	Description string    `json:"description"`
	Tags        *[]string `json:"tags,omitempty"`
	Title       string    `json:"title"`

	// Uuid Stable solution identifier, used with `/v1/solutions/{uuid}`
	Uuid string `json:"uuid"`
}

// UpdateModuleVersionRequest defines model for UpdateModuleVersionRequest.
type UpdateModuleVersionRequest struct {
	// Id Module Version ID
	Id string `json:"id"`

	// Repo Image repo
	Repo string `json:"repo"`

	// Tag Image tag
	Tag string `json:"tag"`
}

// HandleMcpJSONBody defines parameters for HandleMcp.
type HandleMcpJSONBody map[string]interface{}

// ExportSolutionParams defines parameters for ExportSolution.
type ExportSolutionParams struct {
	// Token One-time export token
	Token string `form:"token" json:"token"`
}

// SearchPublicSolutionsParams defines parameters for SearchPublicSolutions.
type SearchPublicSolutionsParams struct {
	// Q Keyword query matched against title, description, and tags
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Tags Tag filter; repeat the parameter for multiple tags
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`

	// Limit Maximum results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PublishModuleJSONRequestBody defines body for PublishModule for application/json ContentType.
type PublishModuleJSONRequestBody = PublishModuleRequest

// UpdateModuleVersionJSONRequestBody defines body for UpdateModuleVersion for application/json ContentType.
type UpdateModuleVersionJSONRequestBody = UpdateModuleVersionRequest

// HandleMcpJSONRequestBody defines body for HandleMcp for application/json ContentType.
type HandleMcpJSONRequestBody HandleMcpJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PublishModuleWithBody request with any body
	PublishModuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PublishModule(ctx context.Context, body PublishModuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateModuleVersionWithBody request with any body
	UpdateModuleVersionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateModuleVersion(ctx context.Context, body UpdateModuleVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthCheck request
	HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HandleMcpWithBody request with any body
	HandleMcpWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	HandleMcp(ctx context.Context, body HandleMcpJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExportSolution request
	ExportSolution(ctx context.Context, params *ExportSolutionParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchPublicSolutions request
	SearchPublicSolutions(ctx context.Context, params *SearchPublicSolutionsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPublicSolution request
	GetPublicSolution(ctx context.Context, uuid string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PublishModuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishModuleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublishModule(ctx context.Context, body PublishModuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishModuleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateModuleVersionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateModuleVersionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateModuleVersion(ctx context.Context, body UpdateModuleVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateModuleVersionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthCheckRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HandleMcpWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHandleMcpRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HandleMcp(ctx context.Context, body HandleMcpJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHandleMcpRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExportSolution(ctx context.Context, params *ExportSolutionParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExportSolutionRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchPublicSolutions(ctx context.Context, params *SearchPublicSolutionsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchPublicSolutionsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPublicSolution(ctx context.Context, uuid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPublicSolutionRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPublishModuleRequest calls the generic PublishModule builder with application/json body
func NewPublishModuleRequest(server string, body PublishModuleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublishModuleRequestWithBody(server, "application/json", bodyReader)
}

// NewPublishModuleRequestWithBody generates requests for PublishModule with any type of body
func NewPublishModuleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/devtools/publish-module")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpdateModuleVersionRequest calls the generic UpdateModuleVersion builder with application/json body
func NewUpdateModuleVersionRequest(server string, body UpdateModuleVersionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateModuleVersionRequestWithBody(server, "application/json", bodyReader)
}

// NewUpdateModuleVersionRequestWithBody generates requests for UpdateModuleVersion with any type of body
func NewUpdateModuleVersionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/devtools/update-module-version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHealthCheckRequest generates requests for HealthCheck
func NewHealthCheckRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHandleMcpRequest calls the generic HandleMcp builder with application/json body
func NewHandleMcpRequest(server string, body HandleMcpJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewHandleMcpRequestWithBody(server, "application/json", bodyReader)
}

// NewHandleMcpRequestWithBody generates requests for HandleMcp with any type of body
func NewHandleMcpRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/mcp")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewExportSolutionRequest generates requests for ExportSolution
func NewExportSolutionRequest(server string, params *ExportSolutionParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/solutions/export")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "token", runtime.ParamLocationQuery, params.Token); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSearchPublicSolutionsRequest generates requests for SearchPublicSolutions
func NewSearchPublicSolutionsRequest(server string, params *SearchPublicSolutionsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/solutions/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Q != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "q", runtime.ParamLocationQuery, *params.Q); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Tags != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tags", runtime.ParamLocationQuery, *params.Tags); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPublicSolutionRequest generates requests for GetPublicSolution
func NewGetPublicSolutionRequest(server string, uuid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/solutions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PublishModuleWithBodyWithResponse request with any body
	PublishModuleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishModuleResponse, error)

	PublishModuleWithResponse(ctx context.Context, body PublishModuleJSONRequestBody, reqEditors ...RequestEditorFn) (*PublishModuleResponse, error)

	// UpdateModuleVersionWithBodyWithResponse request with any body
	UpdateModuleVersionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateModuleVersionResponse, error)

	UpdateModuleVersionWithResponse(ctx context.Context, body UpdateModuleVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateModuleVersionResponse, error)

	// HealthCheckWithResponse request
	HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckResponse, error)

	// HandleMcpWithBodyWithResponse request with any body
	HandleMcpWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HandleMcpResponse, error)

	HandleMcpWithResponse(ctx context.Context, body HandleMcpJSONRequestBody, reqEditors ...RequestEditorFn) (*HandleMcpResponse, error)

	// ExportSolutionWithResponse request
	ExportSolutionWithResponse(ctx context.Context, params *ExportSolutionParams, reqEditors ...RequestEditorFn) (*ExportSolutionResponse, error)

	// SearchPublicSolutionsWithResponse request
	SearchPublicSolutionsWithResponse(ctx context.Context, params *SearchPublicSolutionsParams, reqEditors ...RequestEditorFn) (*SearchPublicSolutionsResponse, error)

	// GetPublicSolutionWithResponse request
	GetPublicSolutionWithResponse(ctx context.Context, uuid string, reqEditors ...RequestEditorFn) (*GetPublicSolutionResponse, error)
}

type PublishModuleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PublishModuleResult
}

// Status returns HTTPResponse.Status
func (r PublishModuleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublishModuleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateModuleVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UpdateModuleVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateModuleVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HealthCheckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r HealthCheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthCheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HandleMcpResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
}

// Status returns HTTPResponse.Status
func (r HandleMcpResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HandleMcpResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ExportSolutionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
}

// Status returns HTTPResponse.Status
func (r ExportSolutionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExportSolutionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SearchPublicSolutionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SolutionSearchResponse
}

// Status returns HTTPResponse.Status
func (r SearchPublicSolutionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchPublicSolutionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPublicSolutionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SolutionDetails
}

// Status returns HTTPResponse.Status
func (r GetPublicSolutionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPublicSolutionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PublishModuleWithBodyWithResponse request with arbitrary body returning *PublishModuleResponse
func (c *ClientWithResponses) PublishModuleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishModuleResponse, error) {
	rsp, err := c.PublishModuleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishModuleResponse(rsp)
}

func (c *ClientWithResponses) PublishModuleWithResponse(ctx context.Context, body PublishModuleJSONRequestBody, reqEditors ...RequestEditorFn) (*PublishModuleResponse, error) {
	rsp, err := c.PublishModule(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishModuleResponse(rsp)
}

// UpdateModuleVersionWithBodyWithResponse request with arbitrary body returning *UpdateModuleVersionResponse
func (c *ClientWithResponses) UpdateModuleVersionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateModuleVersionResponse, error) {
	rsp, err := c.UpdateModuleVersionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateModuleVersionResponse(rsp)
}

func (c *ClientWithResponses) UpdateModuleVersionWithResponse(ctx context.Context, body UpdateModuleVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateModuleVersionResponse, error) {
	rsp, err := c.UpdateModuleVersion(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateModuleVersionResponse(rsp)
}

// HealthCheckWithResponse request returning *HealthCheckResponse
func (c *ClientWithResponses) HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckResponse, error) {
	rsp, err := c.HealthCheck(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthCheckResponse(rsp)
}

// HandleMcpWithBodyWithResponse request with arbitrary body returning *HandleMcpResponse
func (c *ClientWithResponses) HandleMcpWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HandleMcpResponse, error) {
	rsp, err := c.HandleMcpWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHandleMcpResponse(rsp)
}

func (c *ClientWithResponses) HandleMcpWithResponse(ctx context.Context, body HandleMcpJSONRequestBody, reqEditors ...RequestEditorFn) (*HandleMcpResponse, error) {
	rsp, err := c.HandleMcp(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHandleMcpResponse(rsp)
}

// ExportSolutionWithResponse request returning *ExportSolutionResponse
func (c *ClientWithResponses) ExportSolutionWithResponse(ctx context.Context, params *ExportSolutionParams, reqEditors ...RequestEditorFn) (*ExportSolutionResponse, error) {
	rsp, err := c.ExportSolution(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExportSolutionResponse(rsp)
}

// SearchPublicSolutionsWithResponse request returning *SearchPublicSolutionsResponse
func (c *ClientWithResponses) SearchPublicSolutionsWithResponse(ctx context.Context, params *SearchPublicSolutionsParams, reqEditors ...RequestEditorFn) (*SearchPublicSolutionsResponse, error) {
	rsp, err := c.SearchPublicSolutions(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchPublicSolutionsResponse(rsp)
}

// GetPublicSolutionWithResponse request returning *GetPublicSolutionResponse
func (c *ClientWithResponses) GetPublicSolutionWithResponse(ctx context.Context, uuid string, reqEditors ...RequestEditorFn) (*GetPublicSolutionResponse, error) {
	rsp, err := c.GetPublicSolution(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPublicSolutionResponse(rsp)
}

// ParsePublishModuleResponse parses an HTTP response from a PublishModuleWithResponse call
func ParsePublishModuleResponse(rsp *http.Response) (*PublishModuleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublishModuleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PublishModuleResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUpdateModuleVersionResponse parses an HTTP response from a UpdateModuleVersionWithResponse call
func ParseUpdateModuleVersionResponse(rsp *http.Response) (*UpdateModuleVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateModuleVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseHealthCheckResponse parses an HTTP response from a HealthCheckWithResponse call
func ParseHealthCheckResponse(rsp *http.Response) (*HealthCheckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthCheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseHandleMcpResponse parses an HTTP response from a HandleMcpWithResponse call
func ParseHandleMcpResponse(rsp *http.Response) (*HandleMcpResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HandleMcpResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseExportSolutionResponse parses an HTTP response from a ExportSolutionWithResponse call
func ParseExportSolutionResponse(rsp *http.Response) (*ExportSolutionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExportSolutionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSearchPublicSolutionsResponse parses an HTTP response from a SearchPublicSolutionsWithResponse call
func ParseSearchPublicSolutionsResponse(rsp *http.Response) (*SearchPublicSolutionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchPublicSolutionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SolutionSearchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetPublicSolutionResponse parses an HTTP response from a GetPublicSolutionWithResponse call
func ParseGetPublicSolutionResponse(rsp *http.Response) (*GetPublicSolutionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPublicSolutionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SolutionDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /v1/devtools/publish-module)
	PublishModule(w http.ResponseWriter, r *http.Request)

	// (POST /v1/devtools/update-module-version)
	UpdateModuleVersion(w http.ResponseWriter, r *http.Request)

	// (GET /v1/health)
	HealthCheck(w http.ResponseWriter, r *http.Request)

	// (POST /v1/mcp)
	HandleMcp(w http.ResponseWriter, r *http.Request)
	// Export solution using one-time token
	// (GET /v1/solutions/export)
	ExportSolution(w http.ResponseWriter, r *http.Request, params ExportSolutionParams)
	// Search public solutions catalog
	// (GET /v1/solutions/search)
	SearchPublicSolutions(w http.ResponseWriter, r *http.Request, params SearchPublicSolutionsParams)
	// Get full details of a public solution
	// (GET /v1/solutions/{uuid})
	GetPublicSolution(w http.ResponseWriter, r *http.Request, uuid string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PublishModule operation middleware
func (siw *ServerInterfaceWrapper) PublishModule(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, DeveloperTokenScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublishModule(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateModuleVersion operation middleware
func (siw *ServerInterfaceWrapper) UpdateModuleVersion(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, DeveloperTokenScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateModuleVersion(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// HandleMcp operation middleware
func (siw *ServerInterfaceWrapper) HandleMcp(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, DeveloperTokenScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleMcp(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ExportSolution operation middleware
func (siw *ServerInterfaceWrapper) ExportSolution(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportSolutionParams

	// ------------- Required query parameter "token" -------------

	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "token", r.URL.Query(), &params.Token)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportSolution(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SearchPublicSolutions operation middleware
func (siw *ServerInterfaceWrapper) SearchPublicSolutions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchPublicSolutionsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "tags" -------------

	err = runtime.BindQueryParameter("form", true, false, "tags", r.URL.Query(), &params.Tags)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tags", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPublicSolutions(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetPublicSolution operation middleware
func (siw *ServerInterfaceWrapper) GetPublicSolution(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid string

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", mux.Vars(r)["uuid"], &uuid, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicSolution(w, r, uuid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/v1/devtools/publish-module", wrapper.PublishModule).Methods("POST")

	r.HandleFunc(options.BaseURL+"/v1/devtools/update-module-version", wrapper.UpdateModuleVersion).Methods("POST")

	r.HandleFunc(options.BaseURL+"/v1/health", wrapper.HealthCheck).Methods("GET")

	r.HandleFunc(options.BaseURL+"/v1/mcp", wrapper.HandleMcp).Methods("POST")

	r.HandleFunc(options.BaseURL+"/v1/solutions/export", wrapper.ExportSolution).Methods("GET")

	r.HandleFunc(options.BaseURL+"/v1/solutions/search", wrapper.SearchPublicSolutions).Methods("GET")

	r.HandleFunc(options.BaseURL+"/v1/solutions/{uuid}", wrapper.GetPublicSolution).Methods("GET")

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RZ23LbONJ+lS7+/0VSRUsaT640tRe2M5N4Upm4bGfnInLFENESEYMAA4CStSlX7UPs",
	"E+6TbDUASqIEKdIk2b2yKeLQ/fXXR37JCl3VWqFyNht+yWxRYsX8v+eNkPyqseW72gmt/G+10TUaJzA8",
	"MWvn2nD63y1qzIaZdUaoafaUZwZrnXzh2DT5e2PRKFZh4qU/7nMjDPJs+GG1Ml+JEC8Mx9/l7Ql6/AkL",
	"R8e/1byReB2OqVp9uwqZMSvo7/8bnGTD7P/6K3D6EZn+9fnZRecUkm7rtqtmLIUtL9r923dxtIURHtok",
	"HEJN0vjtwCjPam2CUsJhZb+mx6aEV9p4yeOxzBi2iObqHrpt0M6ODVtFO61re3cAXl6aBGYT1kj3kTPH",
	"6JlxLuhIJq/W16UMItkY5bF4WrFhHqEcTtHQ24DjkVJY3Zhi/bax1hKZ2gVbXL8HsRWt0SYQ63r3XyJG",
	"ihTfn7xmwzH3SZhwZcKWP3ycobFRpo6I2c3LNxBfQmORg9MwpgAHrhQWKn9ilm/LtXbi/qAULdauz9eh",
	"P8B+tpEJ80W5DrNYOOrvUYCnPNOrwL1v+1ag3xfRupdsCSz4cWY/GF5BIX4D4xSsW+F5S0RUbCzxTTNG",
	"o9ChvcbgZWdFgXY7NGe/+vXA/GviTa25zcGimYkCbQ4ca6kX/rYchJoatBbtikxLH88zfHSGXTcSD3dH",
	"rxCRIBVp0+pHynTVZrV4ZXRTHxXMyQYBnSO3zdCMj00bW8rcaNmQEV6iY0ImTPNbIyXYuAqsM03hGoNg",
	"0DVGIYfxAu77s5/67Rrb/9I0gj/d90bqQivHhLKAMzQLmEg9h7lwJQhnQWlOpkU+pT9McSi0mohpY5g/",
	"Jx+pWjYWmFosBTiROEMJM2YEMcb2RhQGjsv6JMXh3GgB+k3q+ffI3XnmhJNpTyXc0i7c6tu56YikuLd+",
	"8Ne2cnUTT4vW3R7q/MqnmMqKa7b81hS+QiK8+lgyxXeA6JiZotvzavfmDVyiGJuXLq/YPHAfSJ4+23GS",
	"uH80FT3gCWJ5hzr6tD80x2NougFSy5pweR5V2geFv3B3FZUudtJ+scrdeyvLY6iHzgk1Pc6/Unl0pc9S",
	"zH2g3CAzRXmNttbKJuAxvno53ro3TVUxs/hqDGjP3ytjPGsrR5wbgRPQM0rXOAc9AbZKGXsShfVK+0TB",
	"jBFoAZVupiVMtAFXIhRMSjRUEBhUHA0wCIKC0XOfMjgWguNIzUt0ZVg6QVeUfvuEchcPme2vZIofEds3",
	"ambnC58lWIKjcmIi0OShhvbZMp1ft0vpw+N6yszva84cdorPnT1PSpewE+JWuHyZqvXbkUV362XFplRS",
	"hOnCjmlGagu9yg8pa/dOLrzfF40RbnFD/hN0PEdm0Jw1rqSnsX/6TZuKuWyY/f7nbRYbVF9/+rcrUUrn",
	"ahL9JZUrBNytfkC1nP7s3vK01tl1FfbNQQEfboVawM3CEifvntEuO+z3nVALG37sCd1/DmdXl72RGqkz",
	"KQEVr7VQzoIUM4TGuxI5iCfWPdQGJ+KxB7clxv9BWKiZceTLrsSRso6NhRRuQUWaM6xwQ9CqQGBqebzf",
	"FFoY5PGWcENOBd9I1cyVOVToSs1zMIFcYEtWYygATYx/4TcomFLaQVEyNUUQCthIjQ2yB6GmMGeLHpy3",
	"T2GNBVuKOl7NQOEcKvZJm1arZ/f92Wn/Ph8pdEXvOTCp1dQKjh4NLTlohT76MGo5DBa+fIG5UFzPQwiJ",
	"Lp6t24HQXmuahtmg93NvEPpDVKwW2TD7uTfoDfw4zZWeX4QMx5nTWtp+xO1kldFqHRyvy4JrnArr0LT9",
	"dISNQqyFwqCPH0xar0Td2NLLTAz0mlzylkltm5kFZ0HrzjVfxMrNxTzM6lqKgEH/k9UrArOj+uU2jHh2",
	"J1hty1abKEq27sHONBi6JM8Nj93pYPCjRPVTgoSkN01oXtejRTb88GXLxz/cPd21ueND1lo4u6ONHZs3",
	"PuBGk5+stelp04f43CLVTlpCO+WDIcUNCk9Cq4TVE+H9B9l+TyJJ4LqVNvJtdQ7lww+yWIlMhiwQO4vu",
	"Pa/9ayhKLB6WwXAL/7DqghZl3yD9mqBBLH/tStaqqHdT6O3FFTx7qzlKoNYcHx1cGe10oeXzVRin0HF2",
	"CQRCHMn0RuqsKLB2Fn6/effHyfXVBZz2Bq27Wl/7wY0zyCpf0Ly+vb0CZ5iytTaul6Dja98zvS3qbyDh",
	"4QX60/cOKEdd3TXCEsFWAMoTp4PTbXMFzJHDM6WpKgzS2Oe04cXgp0SIUKxxpTbiH8iPpT0RZ8miVbGJ",
	"j3X8TpDk/nVMPcsKNqz3NOlBnBJaYDBjUvj0euJEheBIhJHSY8cENQczwWBKoFwYZA5/9ad4OVPkCa/b",
	"vsQnVcMqpLzoNe3K+K69NMrm786ozsqG2ecGzaKdew6z9l2XLeufIjaLzbv/HZNuEqDv5MaliiYwtJx0",
	"i0D4DS8SAag9nWqwiW4UT8Qi2/aE0SYrIjSW6rKuwbMV3ZYMS5EuNIY7SReaZV+z1aEqXm6Fgjkm9ZS6",
	"zQdczLXhVCL1qaFkUwpkS8Z6yanp1Eou4N///Bd1XDt6rWVHSi0lVcPtGFSoQjacNPWDsrydalJZ5kch",
	"vgj/s0TlK+VqjNyvFoqjr7LZjAkZmkA0MzQnVI7mYLFiypFmXteRMo2yMBHGul9AU6s7FzaUrZ7BMGFS",
	"Whiz4oF64Fb1ilEvTPWAL1tzWAMyCOlRgXcEwQrEipkH5HAf0P0bucD9SLH1sa/BKTNcorXUI8RGnaIP",
	"FaCB7CnPDaYLvczNkgJfceA3UZugqdcJObApE8o62KfZDi//nO3z6Hzz/ls2hYmQDs0v1KQic4F7rcye",
	"HVUjnagltvfiYy39pCsEkGSwCStXkhw+aLBu4bsQKpGybYnfskdRNVWcltgwQSHL7QBEikq4jijxO3A2",
	"PB3kWRWOy4Y/DehJqPiUb320/eZweNBQqzssS0XGECHaqda+uBWX7gokh4asECi+mif9VEtXtUSHcL/x",
	"9eUearaQmvHYggaZRqq9ZfjjvqOkI8BIdUIAUAQIFaHw3+uUVotKN1YufoHaiBn1J8szRipQDl4MXqRC",
	"wSt03TjwtTCwTEjv3/vhkicytdMrHseR138vex9C1/bbWoKn3a9rvF14cEambE4PwUp7ef4KXWcgGsa0",
	"G7TfxfbNUnJ9NhbKyJC9UmbbHJTERJflWWNkHHzZYb/PatHrjrGyp7un/wQAAP//TM1nAD4lAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
