openapi: "3.0.0"
info:
  version: 0.2.0
  title: Tiny Systems API
  description: Public [Tiny Systems](https://tinysystems.io/) API

servers:
  - url: https://api.tinysystems.io
    description: Tiny Systems API server

paths:
  /health:
    get:
      operationId: health-check
      tags:
        - healthcheck
      description: Health check endpoint
      security: []
      responses:
        200:
          description: Success
  /devtools/publish-module:
    post:
      operationId: publish-module
      tags:
        - devtools
      description: |
        Registers module and returns credentials for push
      security:
        - DeveloperToken: []
      requestBody:
        description: Publish module request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PublishModuleRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublishModuleResult"
  /solutions/export:
    get:
      operationId: export-solution
      tags:
        - solutions
      summary: Export solution using one-time token
      description: |
        Returns solution export JSON. Requires a valid one-time token
        obtained via gRPC CreateExportToken.
      security: []
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
          description: One-time export token
      responses:
        200:
          description: Solution export JSON
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
        401:
          description: Invalid or expired token
        404:
          description: Solution not found
  /devtools/update-module-version:
    post:
      operationId: update-module-version
      tags:
        - devtools
      description: |
        Update module version with image information
      security:
        - DeveloperToken: []
      requestBody:
        description: Module Version ID, image information
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateModuleVersionRequest"
      responses:
        200:
          description: Success
components:
  schemas:
    NodeStatisticsMap:
      type: object
      additionalProperties: {}

    PublishModuleResult:
      type: object
      properties:
        module:
          $ref: "#/components/schemas/PublishModuleVersion"
        options:
          $ref: "#/components/schemas/BuildPushOptions"
    PublishModuleVersion:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        version:
          type: string
      required:
        - id
        - name
        - version
    BuildPushOptions:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        repo:
          type: string
        tag:
          type: string
      required:
        - username
        - password
        - repo
        - tag
    PublishModuleRequest:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        info:
          type: string
        description:
          type: string
        sdk_version:
          type: string
          description: SDK version used to build this module
        components:
          type: array
          items:
            $ref: '#/components/schemas/PublishComponent'
        requirements:
          $ref: '#/components/schemas/ModuleRequirements'
      required:
        - name
        - version
        - components
    ModuleRequirements:
      type: object
      properties:
        rbac:
          $ref: '#/components/schemas/RBACRequirements'
    RBACRequirements:
      type: object
      properties:
        enableKubernetesResourceAccess:
          type: boolean
          description: Enable access to pods, services, deployments, ingresses
        extraRules:
          type: array
          items:
            $ref: '#/components/schemas/RBACRule'
    RBACRule:
      type: object
      properties:
        apiGroups:
          type: array
          items:
            type: string
        resources:
          type: array
          items:
            type: string
        verbs:
          type: array
          items:
            type: string
    PublishComponent:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        info:
          type: string
        tags:
          type: array
          items:
            type: string
        ports:
          type: array
          items:
            $ref: '#/components/schemas/PublishComponentPort'
      required:
        - name
        - description
    PublishComponentPort:
      type: object
      properties:
        name:
          type: string
        label:
          type: string
        source:
          type: boolean
        position:
          type: integer
        schema:
          type: object
          additionalProperties: {}
        default_data:
          type: object
          additionalProperties: {}
      required:
        - name
        - source
    UpdateModuleVersionRequest:
      type: object
      properties:
        id:
          type: string
          description: Module Version ID
        repo:
          type: string
          description: Image repo
        tag:
          type: string
          description: Image tag
      required:
        - id
        - repo
        - tag
  securitySchemes:
    DeveloperToken:
      type: http
      scheme: bearer
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: [ ]


