openapi: "3.0.0"
info:
  version: 1.0.0
  title: Tiny Systems API
  description: Webhook API, Development API

servers:
  - url: https://api.tinysystems.io
    description: Tiny Systems API server

paths:
  /health:
    get:
      operationId: health-check
      tags:
        - healthcheck
      description: Health check endpoint
      security: []
      responses:
        200:
          description: Success
  /webhook/port-data:
    post:
      operationId: port-data-webhook
      tags:
        - webhooks
      description: |
        Receives port data from a tiny tracker
      security:
        - BearerAuth: []
      requestBody:
        description: Port binary data
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      parameters:
        - in: header
          name: X-TinySystems-Port-Full-Name
          schema:
            type: string
          required: true
        - in: header
          name: X-TinySystems-Flow-Id
          schema:
            type: string
          required: true
        - in: header
          name: X-TinySystems-Edge-Id
          schema:
            type: string
        - in: header
          name: X-TinySystems-Error
          description: If current data describes an error
          schema:
            type: string
      responses:
        200:
          description: Success
  /webhook/statistics:
    post:
      operationId: port-data-statistics
      tags:
        - webhooks
      description: |
        Receives statistics information from a tiny tracker
      security:
        - BearerAuth: []
      requestBody:
        description: Statistics key value object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NodeStatisticsMap"
      parameters:
        - in: header
          name: X-TinySystems-Node-Name
          schema:
            type: string
          required: true
        - in: header
          name: X-TinySystems-Flow-Id
          schema:
            type: string
          required: true
      responses:
        200:
          description: Success
  /devtools/publish-module:
    post:
      operationId: publish-module
      tags:
        - devtools
      description: |
        Registers module and returns credentials for it's push
      security:
        - DeveloperToken: []
      requestBody:
        description: Publish module request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PublishModuleRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublishModuleResult"
  /devtools/update-module-version:
    post:
      operationId: update-module-version
      tags:
        - devtools
      description: |
        Update module version with image information
      security:
        - DeveloperToken: []
      requestBody:
        description: Module Version ID, image information
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateModuleVersionRequest"
      responses:
        200:
          description: Success
components:
  schemas:
    NodeStatisticsMap:
      type: object
      additionalProperties: {}

    PublishModuleResult:
      type: object
      properties:
        module:
          $ref: "#/components/schemas/PublishModuleVersion"
        options:
          $ref: "#/components/schemas/BuildPushOptions"
    PublishModuleVersion:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        version:
          type: string
      required:
        - id
        - name
        - version
    BuildPushOptions:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        repo:
          type: string
        tag:
          type: string
      required:
        - username
        - password
        - repo
        - tag
    PublishModuleRequest:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        info:
          type: string
        description:
          type: string
        components:
          type: array
          items:
            $ref: '#/components/schemas/PublishComponent'
      required:
        - name
        - version
        - components
    PublishComponent:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        info:
          type: string
        tags:
          type: array
          items:
            type: string
      required:
        - name
        - description
    UpdateModuleVersionRequest:
      type: object
      properties:
        id:
          type: string
          description: Module Version ID
        repo:
          type: string
          description: Image repo
        tag:
          type: string
          description: Image tag
      required:
        - id
        - repo
        - tag
  securitySchemes:
    DeveloperToken:
      type: http
      scheme: bearer
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: [ ]


